apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-pod
  labels:
{{ include "dedicate-node-labeling.labels" . | indent 4 }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-role
  labels:
{{ include "dedicate-node-labeling.labels" . | indent 4 }}

rules:
  - apiGroups: [""]
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
      - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-node-editable
  labels:
{{ include "dedicate-node-labeling.labels" . | indent 4 }}

subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-pod
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-role
  apiGroup: rbac.authorization.k8s.io
